FROM oven/bun:1.3.6 AS builder

WORKDIR /usr/src/app

COPY server/package.json ./
COPY server/bun.lock ./

RUN bun ci

COPY shared/ ./shared/

COPY server/tsconfig.docker.json ./tsconfig.json

COPY server/src/ ./src/

RUN bun run build

FROM oven/bun:1.3.6-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app/dist ./dist

COPY server/.production.env ./.env

EXPOSE 3123

CMD ["bun", "run", "start"]
