FROM oven/bun:1.3.6 AS builder

WORKDIR /usr/src/app

COPY matchmaker/package.json ./
COPY matchmaker/bun.lock ./

RUN bun ci

COPY shared/ ./shared

COPY matchmaker/tsconfig.docker.json ./tsconfig.json
COPY matchmaker/src/ ./src/

RUN bun run build

FROM oven/bun:1.3.6-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app/dist ./dist

COPY matchmaker/.production.env ./.env

EXPOSE 3000

CMD ["bun", "run", "start"]
