export const male_names = [
    'Firion',
    'Guy',
    'Leon',
    'Minwu',
    'Josef',
    'Gordon',
    'Ricard',
    'Luneth',
    'Arc',
    'Ingus',
    'Cecil',
    'Kain',
    'Tellah',
    'Edward',
    'Yang Fang',
    'Palom',
    'Fusoya',
    'Cid',
    'Bartz',
    'Galuf',
    'Biggs',
    'Wedge',
    'Locke',
    'Edgar',
    'Shadow',
    'Cyan',
    'Gau',
    'Setzer',
    'Strago',
    'Mog',
    'Umaro',
    'Cloud',
    'Barret',
    'Red',
    'Vincent',
    'Reeve',
    'Sephi',
    'Squall',
    'Zell',
    'Irvine',
    'Seifer',
    'Laguna',
    'Kiros',
    'Ward',
    'Djidane',
    'Bibi',
    'Steiner',
    'Tarask',
    'Tidus',
    'Wakka',
    'Kimahri',
    'Auron',
    'Serge',
    'Crono',
    'Marth',
    'Ike',
    'Garland',
    'Kuja',
    'Seymour',
    'Isaac',
    'Gareth',
    'Ivan',
    'Felix',
    'Piers',
    'Kraden',
    'Saturos',
    // 'Eddard',
    // 'Robb',
    // 'Jon',
    // 'Bran',
    // 'Rickon',
    // 'Tyrion',
    // 'Jaime',
    // 'Jorah',
    // 'Theon',
    // 'Samwell',
    // 'Tywin',
    // 'Sandor',
    // 'Gregor',
    // 'Petyr',
    // 'Varys',
    // 'Barristan',
    // 'Rhaegar',
    // 'Robert',
    // 'Renly',
    // 'Stannis',
    // 'Joffrey',
    // 'Tommen',
    // 'Ramsay',
    // 'Viserys',
    // 'Drogo',
    // 'Jaqen',
    // 'Syrio',
    // 'Beric',
    // 'Thoros',
    // 'Gendry',
    // 'Podrick',
    // 'Bronn',
    // 'Loras',
    // 'Oberyn',
    // 'Doran',
    // 'Euron',
    // 'Balon',
    // 'Victarion',
    // 'Aeron',
    // 'Qyburn',
    // 'Roose',
    // 'Walder',
    // 'Mance',
    // 'Tormund',
    // 'Daario',
    // 'Mace',
    // 'Brynden',
    // 'Edmure',
    // 'Jeor'
];

export const female_names = [
    'Maria',
    'Leila',
    'Refia',
    'Rosa',
    'Rydia',
    'Porom',
    'Lena',
    'Faris',
    'Krile',
    'Terra',
    'Celes',
    'Relm',
    'Tifa',
    'Aerith',
    'Yuffie',
    'Linoa',
    'Quistis',
    'Selphie',
    'Edea',
    'Dagga',
    'Freija',
    'Quina',
    'Eiko',
    'Yuna',
    'Lulu',
    'Rikku',
    'Lucca',
    'Lyn',
    'Adel',
    'Menardi',
    'Mia',
    // 'Catelyn',
    // 'Sansa',
    // 'Arya',
    // 'Daenerys',
    // 'Cersei',
    // 'Brienne',
    // 'Asha',
    // 'Shae',
    // 'Meera',
    // 'Osha',
    // 'Myrcella',
    // 'Ellaria',
    // 'Missandei',
    // 'Gilly',
    // 'Ygritte',
    // 'Melisandre',
    // 'Margaery',
    // 'Olenna',
    // 'Selyse',
    // 'Lyanna',
    // 'Shireen',
    // 'Talisa',
    // 'Roslin',
    // 'Walda',
    // 'Tansy',
    // 'Yara',
    // 'Val',
    // 'Doreah',
    // 'Irri',
    // 'Jhiqui',
];