export const tips = [
    "You earn gold while queuing for a match. The longer you queue, the higher the reward. Patience pays off!",
    "Teaching spells to characters cannot be undone (for now) and will consume the spell, so choose wisely!",
    "Regularly play Casual or Ranked games to win the keys to your daily loot chests!",
    "Your characters earn SP when leveling-up. Spend them to increase their stats!",
    "If your mages often lack MP during a game, consider equipping them with Ethers!",
    "The Poison spell is a great way to deal damage over time to your enemies!",
    "Fire spells set the ground on fire, dealing damage to any character standing on or crossing it!",
    "Ice spells can freeze your enemies, preventing them from moving or attacking until freed!",
    "The only way to free a frozen character is to attack them with a melee attack or use a fire spell on them!",
    "Thunder spells can paralyze your enemies, preventing them from moving or attacking for a limited time!",
    "The + and X versions of spells tend to have larger areas of effect and deal more damage!",
    "Every action in the game has a cooldown time. While a character is in cooldown, they cannot do anything, but you can still use your other characters in the meantime!",
    "Targetting ice spells on an empty cell will still create ice blocks that can be used to block your enemies' path!",
    "The HP and MP of your whole team are fully replenished after each combat, so don't be afraid to use your spells!",
    "You can revive characters during combat by using a Clover!",
    "The bar at the bottom of the game screen is the Audience bar. Impress the audience to earn extra rewards!",
    "Haste Potions cut your cooldowns in half, very useful before casting a powerful spell!",
];

export const guide = [
    "You have a lot of gold, champion! Click here to go to the shop and buy something nice for your characters!",
    "One of your characters has unspent SP! Click here to go to the team page and spend them to increase their stats!",
    "A key for one of your daily loot chests is ready to be won! Click here to start a Casual game and win it!",
    "You have unused equipment pieces in your inventory! Click here to go to the team page and equip them!",
    "You have unused consumables in your inventory! Click here to go to the team page and equip them on your characters!",
    "You have unused spells in your inventory! Click here to go to the team page and teach them to your characters!",
    "Not sure what to do? Just click here to start a Practice game and try out your characters and spells!",
    "Now that you know the game a bit more, click here to play against another player in Casual mode!",
    "You've had a few victories now, why don't you try your luck in Ranked mode and climb the ladder? Click here to start!",
    "Your characters know cool spells, why don't you give them a try in combat?",
];